![transparent-logo_resize.png]()

# Python for Data Science (ML and DL)

#Python Language Basics

In this section, I will give you an overview of essential Python programming concepts
and language mechanics. In the next chapter, I will go into more detail about Python’s
data structures, functions, and other built-in tools.

### Language Semantics

The Python language design is distinguished by its emphasis on readability, simplic‐
ity, and explicitness. Some people go so far as to liken it to “executable pseudocode.

#### **Indentation, not braces**

Python uses whitespace (tabs or spaces) to structure code instead of using braces as in
many other languages like R, C++, Java, and Perl. 

Consider a for loop from a sorting
algorithm:

In [ ]:
# less = []
# greater = []

# array = [1,2,3,4,5,6]
# pivot = 4

# for x in array:

#   if x < pivot:
#     less.append(x)
#   else:
#     greater.append(x)

A colon denotes the start of an indented code block after which all of the code must
be indented by the same amount until the end of the block.


Love it or hate it, significant whitespace is a fact of life for Python programmers, and
in my experience it can make Python code more readable than other languages I’ve
used. 

While it may seem foreign at first, you will hopefully grow accustomed in time.

As you can see by now, Python statements also do not need to be terminated by semi‐
colons. Semicolons can be used, however, to separate multiple statements on a single
line:


`a = 5; b = 6; c = 7`


Putting multiple statements on one line is generally discouraged in Python as it often
makes code less readable.

#### **Comments**

Any text preceded by the hash mark (pound sign) # is ignored by the Python inter‐preter. This is often used to add comments to code. 


At times you may also want to exclude certain blocks of code without deleting them. An easy solution is to comment
out the code:

In [ ]:
# This is a comment

Comments can also occur after a line of executed code. 

While some programmers prefer comments to be placed in the line preceding a particular line of code, this can be useful at times:

In [ ]:
print("Reached this line") # Simple status report

### **Function and object method calls**

You call functions using parentheses and passing zero or more arguments, optionally assigning the returned value to a variable:

In [ ]:
# result = f(x, y, z)
# g()

Almost every object in Python has attached functions, known as methods, that have access to the object’s internal contents. 


You can call them using the following syntax: 
`obj.some_method(x, y, z)`

**Functions can take both positional and keyword arguments:**

`result = f(a, b, c, d=5, e='foo')`

**More on this later.**

### **Variables and argument passing**

When assigning a variable (or name) in Python, you are creating a reference to the object on the righthand side of the equals sign. 


In practical terms, consider a list of integers:

In [ ]:
a = [1, 2, 3]

Suppose we assign a to a new variable b:

In [ ]:
b = a

**NOTE:** 

In some languages, this assignment would cause the data `[1, 2, 3]` to be copied. 

In Python, a and b actually now refer to the same object, the original list `[1, 2, 3]`

You can prove this to yourself by appending an element to
a and then examining b:

In [ ]:
a.append(4)

In [ ]:
print(b)

### **Dynamic references, strong types**

There is no problem with the following:

In [ ]:
a = 5

In [ ]:
type(a)

In [ ]:
a = 'foo'

In [ ]:
type(a)

Variables are names for objects within a particular namespace; the type information is stored in the object itself.


Consider this example:

In [ ]:
#Expected error 
'5' + 5

In some languages, such as Visual Basic, the string '5' might get implicitly converted (or casted) to an integer, thus yielding 10.


Yet in other languages, such as JavaScript,the integer 5 might be casted to a string, yielding the concatenated string '55'.


In this
regard Python is considered a **strongly typed language**, which means that every object
has a specific type (or class), and implicit conversions will occur only in certain obvi‐
ous circumstances, such as the following:

In [ ]:
a = 4.5

In [ ]:
b = 2

In [ ]:
# String formatting, to be visited later
print('a is {0}, b is {1}'.format(type(a), type(b)))

In [ ]:
a / b

Knowing the type of an object is important, and it’s useful to be able to write functions that can handle many different kinds of input. 


You can check that an object is an instance of a particular type using the `isinstance` function:

In [ ]:
a = 5

In [ ]:
isinstance(a, int)

`isinstance` can accept a tuple of types if you want to check that an object’s type is among those present in the tuple:

In [ ]:
a = 5; b = 4.5

In [ ]:
isinstance(a, (int, float))

In [ ]:
isinstance(b, (int, float))

### **Attributes and methods**

Objects in Python typically have both attributes (other Python objects stored “inside” the object) and methods (functions associated with an object that can have access to
the object’s internal data). 


Both of them are accessed via the syntax `obj.attribute_name`:

In [ ]:
a = 'foo'

In [ ]:
# a.<Shift + Press Tab>

Attributes and methods can also be accessed by name via the `getattr` function:

In [ ]:
getattr(a, 'split')

### **Duck typing**

Often you may not care about the type of an object but rather only whether it has certain methods or behavior. 

This is sometimes called “duck typing,” after the saying 
`“If it walks like a duck and quacks like a duck, then it’s a duck.”` 

For example, you can verify that an object is iterable if it implemented the iterator protocol. 

For many objects, this means it has a `__iter__` “**magic method**,” though an alternative and better way to check is to try using the `iter function`:

In [ ]:
def isiterable(obj):
  try:
    iter(obj)

    return True

  except TypeError:# not iterable     

    return False

This function would return `True` for strings as well as most Python collection types:

In [ ]:
isiterable('a string')

In [ ]:
isiterable([1, 2, 3])

In [ ]:
isiterable(5)

### **Imports**

In Python a `module` is simply a file with the `.py` extension containing Python code.


Suppose that we had the following module:

In [ ]:
# some_module.py
# Created a file named some_module.py and contains the following code

# PI = 3.14159
# def f(x):
#  return x + 2
# def g(a, b):
#  return a + b

If we wanted to access the variables and functions defined in `some_module.py`, from another file in the same directory we could do:

In [ ]:
import some_module

In [ ]:
result = some_module.f(5)

pi = some_module.PI

**Or equivalently:**

In [ ]:
from some_module import f, g, PI

result = g(5, PI)

By using the `as` keyword you can give imports different variable names:

In [ ]:
import some_module as sm
from some_module import PI as pi, g as gf

In [ ]:
r1 = sm.f(pi)
r2 = gf(6, pi)

### **Binary operators and comparisons**

Most of the binary math operations and comparisons are as you might expect:

In [ ]:
5 - 7

In [ ]:
12 + 21.5

In [ ]:
5 <= 2

To check if two references refer to the same object, use the `is` keyword. 

`is not` is also perfectly valid if you want to check that two objects are not the same:

In [ ]:
a = [1, 2, 3]

In [ ]:
b = a

In [ ]:
c = list(a)

In [ ]:
a is b

In [ ]:
a is not c

Since `list` always creates a new Python list (i.e., a copy), we can be sure that `c` is distinct from `a`. 


Comparing with `is` is not the same as the `==` operator, because in this case we have:

In [ ]:
a == c

A very common use of is and is not is to check if a variable is `None`, since there is only one instance of `None`:

In [ ]:
a = None

In [ ]:
a is None

**Binary operators**

**Operation** -- **Discription**

`a + b`   Add a and b

`a - b` Subtract b from a

`a * b` Multiply a by b

`a / b` Divide a by b

`a // b` Floor-divide a by b, dropping any fractional remainder

`a ** b` Raise a to the b power

`a & b` True if both a and b are True; for integers, take the bitwise AND

`a | b` True if either a or b is True; for integers, take the bitwise OR

`a ^ b` For booleans, True if a or b is True, but not both; for integers, take the bitwise EXCLUSIVE-OR

`a == b` True if a equals b

`a != b` True if a is not equal to b

`a <= b, a < b` True if a is less than (less than or equal) to b

`a > b, a >= b` True if a is greater than (greater than or equal) to b

`a is b` True if a and b reference the same Python object

`a is not b` True if a and b reference different Python objects

### **Mutable and immutable objects**

Most objects in Python, such as lists, dicts, NumPy arrays, and most user-defined types (classes), are mutable. 


This means that the object or values that they contain can be modified:

In [ ]:
a_list = ['foo', 2, [4, 5]]

In [ ]:
a_list[2] = (3, 4)

In [ ]:
a_list

Others, like strings and tuples, are immutable:

In [ ]:
a_tuple = (3, 5, (4, 5))

In [ ]:
a_tuple[1] = 'four'

### **Numeric Types**

The primary Python types for numbers are int and float. 

An int can store arbitrarily large numbers:

In [ ]:
ival = 17239871

In [ ]:
ival ** 6

Floating-point numbers are represented with the Python float type. Under the hood each one is a double-precision (64-bit) value. 


They can also be expressed with scientific notation:

In [ ]:
fval = 7.243

In [ ]:
fval2 = 6.78e-5

Integer division not resulting in a whole number will always yield a floating-point number:

In [ ]:
3 / 2

To get C-style integer division (which drops the fractional part if the result is not a whole number), use the floor division operator 
`//`:

In [ ]:
3 // 2

### **Strings**

You can write string literals using either single quotes `'` or double quotes `"`:

In [ ]:
a = 'one way of writing a string'

b = "another way"

For multiline strings with line breaks, you can use triple quotes, either `''' or """`:

In [ ]:
c = """
This is a longer string that
spans multiple lines
"""

In [ ]:
c.count('\n')

Python strings are immutable; you cannot modify a string:

In [ ]:
a = 'this is a string'

In [ ]:
#  a[10] = 'f'

Many Python objects can be converted to a string using the `str` function:

In [ ]:
a = 5.6

In [ ]:
s = str(a)

In [ ]:
print(s)

Strings are a sequence of **Unicode** characters and therefore can be treated like other sequences, such as lists and tuples (which we will explore in more detail in the next
chapter):

In [ ]:
s = 'python'

In [ ]:
list(s)

In [ ]:
s[:3]

The syntax `s[:3]` is called slicing and is implemented for many kinds of Python sequences. This will be explained in more detail later on

The backslash character \ is an escape character, meaning that it is used to specify special characters like newline \n or Unicode characters. 

To write a string literal with backslashes, you need to escape them:

In [ ]:
s = '12\\34'

In [ ]:
print(s)

**String Concatenation**

Adding two strings together concatenates them and produces a new string:

In [ ]:
a = 'this is the first half '

b = 'and this is the second half'

a + b

**String Formatting**

String objects have a format method that can be used to substitute formatted arguments into the string, producing a new string

In [ ]:
template = '{0:.2f} {1:s} are worth US${2:d}'

In this string,

- {0:.2f} means to format the first argument as a floating-point number with two decimal places.

- {1:s} means to format the second argument as a string.

- {2:d} means to format the third argument as an exact integer.


To substitute arguments for these format parameters, we pass a sequence of arguments to the format method:

In [ ]:
template.format(4.5560, 'Argentine Pesos', 1)

String formatting is a deep topic; there are multiple methods and numerous options and tweaks available to control how values are formatted in the resulting string. 

To learn more, I recommend consulting the [official Python documentation](https://docs.python.org/3.6/library/string.html).

### **Booleans**

The two boolean values in Python are written as True and False. 

Comparisons and other conditional expressions evaluate to either True or False. 

Boolean values are combined with the and and or keywords:

In [ ]:
True and True

In [ ]:
False or True

### **Type casting**

The str, bool, int, and float types are also functions that can be used to cast values to those types:

In [ ]:
s = '3.14159'

In [ ]:
fval = float(s)

In [ ]:
type(fval)

In [ ]:
int(fval)

In [ ]:
bool(fval)

In [ ]:
bool(0)

### **None**


None is the Python null value type. If a function does not explicitly return a value, it implicitly returns None:

In [ ]:
a = None

In [ ]:
a is None

In [ ]:
b = 5

In [ ]:
#  b is not None

`None` is also a common default value for function arguments:

In [ ]:
def add_and_maybe_multiply(a, b, c=None):

  result = a + b
  if c is not None:
    result = result * c
    
  return result

While a technical point, it’s worth bearing in mind that `None` is not only a reserved keyword but also a unique instance of `NoneType`:

In [ ]:
type(None)

## **Control Flow**

#### **if, elif, and else**

The if statement is one of the most well-known control flow statement types. It checks a condition that, if True, evaluates the code in the block that follows:

In [ ]:
if x < 0:
 print('It's negative')

An if statement can be optionally followed by one or more `elif` blocks and a catchall `else` block if all of the conditions are False:

In [ ]:
if x < 0:
  print('It's negative')
elif x == 0:
  print('Equal to zero')
elif 0 < x < 5:
  print('Positive but smaller than 5')
else:
  print('Positive and larger than or equal to 5')

If any of the conditions is True, no further elif or else blocks will be reached. 

With a compound condition using `and` or `or`, conditions are evaluated left to right and will short-circuit:

In [ ]:
a = 5; b = 7

In [ ]:
c = 8; d = 4

In [ ]:
if a < b or c > d:
  print('Made it')

In this example, the comparison `c > d` never gets evaluated because the first comparison was `True`.

### **for loops**


for loops are for iterating over a collection (like a list or tuple) or an iterater. 

The standard syntax for a for loop is:

In [ ]:
for value in collection:
 # do something with value

You can advance a for loop to the next iteration, skipping the remainder of the block, using the `continue` keyword. 

Consider this code, which sums up integers in a list and skips `None` values:

In [ ]:
sequence = [1, 2, None, 4, None, 5]
total = 0

for value in sequence:
  if value is None:
    continue
  total += value

A `for` loop can be exited altogether with the `break` keyword. 

This code sums elements of the list until a 5 is reached

In [ ]:
sequence = [1, 2, 0, 4, 6, 5, 2, 1]
total_until_5 = 0

for value in sequence:
  if value == 5:
    break
  total_until_5 += value

**NOTE:** The break keyword only terminates the innermost for loop; any outer for loops will continue to run:

In [ ]:
for i in range(4):

  for j in range(4):

    if j > i:

      break
      
    print((i, j))

As we will see in more detail, if the elements in the collection or iterator are sequences (tuples or lists), they can be conveniently unpacked into variables in the for loop statement:

`for a, b, c in iterator:`

### **while loops**

A `while` loop specifies a condition and a block of code that is to be executed until the condition evaluates to `False` or the loop is explicitly ended with `break`:

In [ ]:
x = 256
total = 0

while x > 0:

  if total > 500:
    break

  total += x
  x = x // 2

### **pass**

pass is the `“no-op”` statement in Python. It can be used in blocks where no action is to be taken (or as a placeholder for code not yet implemented); 

it is only required because Python uses whitespace to delimit blocks:

In [ ]:
if x < 0:

  print('negative!')
  
elif x == 0:

  # TODO: put something smart here
  pass

else:

  print('positive!')

### **range**

The range function returns an iterator that yields a sequence of evenly spaced integers:

In [2]:
range(10)

In [ ]:
list(range(10))

A start, end, and step (which may be negative) can be given:

In [ ]:
list(range(0, 20, 2))

In [ ]:
list(range(5, 0, -1))

As you can see, `range` produces integers up to but not including the **endpoint**. A common use of `range` is for iterating through sequences by index:

In [ ]:
seq = [1, 2, 3, 4]

for i in range(len(seq)):

  val = seq[i]

### **Ternary expressions**

A ternary expression in Python allows you to combine an if-else block that produces a value into a single line or expression. 

The syntax for this in Python is:

```
value = true-expr if condition else false-expr

```


Here, true-expr and false-expr can be any Python expressions. It has the identical effect as the more verbose represensation:



```
if condition:
 value = true-expr
else:
 value = false-expr
```


This is a more concrete example:

In [ ]:
x = 5

In [ ]:
'Non-negative' if x >= 0 else 'Negative'

**NOTE:**

While it may be tempting to always use ternary expressions to condense your code, realize that you may sacrifice readability if the condition as well as the true and false expressions are very complex.

# Built-in Data Structures, Functions,and Files

Here, We’ll start with Python’s workhorse data structures: tuples, lists, dicts, and sets. 

Then,we’ll discuss creating your own reusable Python functions. 

Finally, we’ll look at the mechanics of Python file objects and interacting with your local hard drive.

## **Data Structures and Sequences**

Python’s data structures are simple but powerful. Mastering their use is a critical part of becoming a proficient Python programmer.

### **Tuple**

A tuple is a fixed-length, immutable sequence of Python objects. 

The easiest way to create one is with a comma-separated sequence of values:

In [ ]:
tup = 4, 5, 6

In [ ]:
tup

**NOTE:** When you’re defining tuples in more complicated expressions, it’s often necessary to enclose the values in parentheses, as in this example of creating a tuple of tuples:

In [ ]:
nested_tup = (4, 5, 6), (7, 8)

In [ ]:
nested_tup

You can convert any sequence or iterator to a tuple by invoking `tuple`:

In [ ]:
tuple([4, 0, 2])

In [ ]:
tup = tuple('string')

In [ ]:
tup

Elements can be accessed with square brackets `[]` as with most other sequence types.

In Python and many other programming languages, sequences are 0-indexed:

In [ ]:
tup[0]

While the objects stored in a tuple may be mutable themselves, once the tuple is created it’s not possible to modify which object is stored in each slot:

In [ ]:
tup = tuple(['foo', [1, 2], True])

In [ ]:
#Expected Error
tup[2] = False

**NOTE:** If an object inside a tuple is mutable, such as a list, you can modify it in-place:

In [ ]:
tup[1].append(3)

In [ ]:
tup

You can concatenate tuples using the `+` operator to produce longer tuples:

In [ ]:
(4, None, 'foo') + (6, 0) + ('bar',)

Multiplying a tuple by an integer, as with lists, has the effect of concatenating together that many copies of the tuple:

In [ ]:
('foo', 'bar') * 4

**Unpacking tuples**

If you try to assign to a *tuple-like* expression of variables, Python will attempt to **unpack** the value on the righthand side of the equals sign:

In [3]:
tup = (4, 5, 6)

In [4]:
a, b, c = tup

In [ ]:
b

In [6]:
# a,b = tup

Even sequences with nested tuples can be unpacked:

In [7]:
tup = 4, 5, (6, 7)

In [ ]:
a, b, (c, d) = tup

In [9]:
d

Using this functionality you can easily swap variable names, a task which in many languages might look like:

```
tmp = a
a = b
b = tmp

```

But, in Python, the swap can be done like this:

In [ ]:
a, b = 1, 2

In [ ]:
a

In [ ]:
b

In [ ]:
b,a = a,b

In [ ]:
a

In [ ]:
b

A common use of variable unpacking is iterating over sequences of tuples or lists:

In [ ]:
seq = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]

In [ ]:
for a, b, c in seq:

  print('a={0}, b={1}, c={2}'.format(a, b, c))

Another common use is returning multiple values from a function. I’ll cover this in more detail later.

The Python language recently acquired some more advanced tuple unpacking to help with situations where you may want to “pluck” a few elements from the beginning of a tuple. 

This uses the special syntax `*rest`,

In [ ]:
values = 1, 2, 3, 4, 5

In [ ]:
a, b, *rest = values

In [ ]:
a, b

In [ ]:
rest

This `rest` bit is sometimes something you want to discard; **there is nothing special about the rest name**. 


As a matter of convention, many Python programmers will use
the underscore `(_)` for unwanted variables:

In [ ]:
a, b, *_ = values

**Tuple methods**

Since the size and contents of a tuple cannot be modified, it is very light on instance methods. 

A particularly useful one (also available on lists) is `count`, which counts the number of occurrences of a value:

In [10]:
a = (1, 2, 2, 2, 3, 4, 2)

In [ ]:
a.count(2)

### **List**

In contrast with tuples, lists are variable-length and their contents can be modified in-place. 

You can define them using square brackets `[]` or using the `list` type function:

In [12]:
a_list = [2, 3, 7, None]

In [ ]:
tup = ('food', 'bar', 'baz')

In [ ]:
b_list = list(tup)

In [ ]:
b_list

In [ ]:
b_list[1] = 'peekaboo'

In [ ]:
b_list

The `list` function is frequently used in data processing as a way to materialize an iterator or generator expression:

In [ ]:
gen = range(10)

In [ ]:
gen

In [ ]:
list(gen)

##### **Adding and removing elements**

Elements can be appended to the end of the list with the `append` method:

In [ ]:
b_list.append('dwarf')

In [ ]:
b_list

Using `insert` you can insert an element at a specific location in the list:

In [ ]:
b_list.insert(1, 'red')

In [ ]:
b_list

**NOTE:** The insertion index must be between 0 and the length of the list

**ATTENTION**

`insert` is computationally expensive compared with `append`,
because references to subsequent elements have to be shifted inter‐
nally to make room for the new element. 

If you need to insert elements at both the beginning and end of a sequence, you may wish to explore `collections.deque`, a double-ended queue, for this purpose.

The inverse operation to `insert` is `pop`, which removes and returns an element at a particular index:

In [ ]:
b_list.pop(2)

In [ ]:
b_list

Elements can be removed by value with `remove`, which locates the first such value and removes it :

In [ ]:
b_list.append('food')

In [ ]:
b_list

In [ ]:
b_list.remove('food')

In [ ]:
b_list

Check if a list contains a value using the `in` keyword:

In [ ]:
'dwarf' in b_list

The keyword `not` can be used to negate in:

In [ ]:
'dwarf' not in b_list

**NOTE:** Checking whether a list contains a value is a lot slower than doing so with dicts and sets (to be introduced shortly), as Python makes a linear scan across the values of the list, whereas it can check the others (based on hash tables) in constant time.

##### **Concatenating and combining lists**


Similar to tuples, adding two lists together with + concatenates them:

In [ ]:
[4, None, 'foo'] + [7, 8, (2, 3)]

If you have a list already defined, you can append multiple elements to it using the `extend` method:

In [ ]:
x = [4, None, 'foo']

In [ ]:
x.extend([7, 8, (2, 3)])

In [ ]:
x

**Note** 

list concatenation by addition is a comparatively expensive operation since a new list must be created and the objects copied over. 

Using extend to append elements to an existing list, especially if you are building up a large list, is usually preferable. Thus,

```
everything = []
for chunk in list_of_lists:
  everything.extend(chunk)

```

is faster than the concatenative alternative:

```
everything = []
for chunk in list_of_lists:
  everything = everything + chunk

```

#### **Sorting**

You can sort a list in-place (without creating a new object) by calling its sort function:

In [ ]:
a = [7, 2, 5, 1, 3]

In [ ]:
a.sort()

In [ ]:
a

`sort` has a few options that will occasionally come in handy. 

One is the ability to pass a secondary *sort key*— that is, a function that produces a value to use to sort the objects. 

For example, we could sort a collection of strings by their lengths:

In [ ]:
b = ['saw', 'small', 'He', 'foxes', 'six']

In [ ]:
b.sort(key=len)

In [ ]:
b

Soon, we’ll look at the `sorted` function, which can produce a sorted copy of a general sequence.

#### **Binary search and maintaining a sorted list**


The built-in bisect module implements binary search and insertion into a sorted list.

`bisect.bisect` finds the location where an element should be inserted to keep it sorted, while `bisect.insort` actually inserts the element into that location:

In [ ]:
import bisect

In [ ]:
c = [1, 2, 2, 2, 3, 4, 7]

In [ ]:
bisect.bisect(c, 2)

In [ ]:
bisect.bisect(c, 5)

In [ ]:
bisect.insort(c, 6)

**ATTENTION**

The `bisect` module functions do not check whether the list is sor‐
ted, as doing so would be computationally expensive. Thus, using
them with an unsorted list will succeed without error but may lead
to incorrect results.

#### **Slicing**

You can select sections of most sequence types by using slice notation, which in its basic form consists of `start:stop` passed to the indexing operator `[]`

In [ ]:
seq = [7, 2, 3, 7, 5, 6, 0, 1]

In [ ]:
seq[1:5]

Slices can also be assigned to with a sequence:

In [ ]:
seq[3:4] = [6, 3]

In [ ]:
seq

While the element at the start index is included, the stop index is not included, sothat the number of elements in the result is 
*stop - start*.

Either the start or stop can be omitted, in which case they default to the start of the sequence and the end of the sequence, respectively:

In [ ]:
seq[:5]

In [ ]:
seq[3:]

Negative indices slice the sequence relative to the end:

In [ ]:
seq[-4:]

In [ ]:
seq[-6:-2]

A `step` can also be used after a second colon to, say, take every other element:

In [ ]:
seq[::2]

A clever use of this is to pass `-1`, which has the useful effect of reversing a list or tuple:

In [ ]:
seq[::-1]

#### **Built-in Sequence Functions**